# Generated by Django 5.2.7 on 2026-04-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0023_notificacion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='decisiondocenteajuste',
            name='unique_decision_docente_ajuste',
        ),
        migrations.AlterUniqueTogether(
            name='decisiondocenteajuste',
            unique_together={('ajuste_asignado', 'docente')},
        ),
    ]
